# Practice 12

# Numpy

### Exercise 1

In [3]:
import numpy as np

arr = np.zeros((4,5,3))
print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [4]:
print(arr.shape)

(4, 5, 3)


In [9]:
print(arr.ndim)

3


### Excercise 2

In [6]:
new_arr = a.reshape(20,3)
print(new_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
print(new_arr.shape)

(20, 3)


In [8]:
print(new_arr.ndim)

2


### Exercise3

In [10]:
arr= np.array([[10,20,30,40],
               [50,60,70,80]
               ])

In [11]:
print(arr[1,0])

50


### Exercise 4

In [12]:
arr= np.array([[10,20,30,40],
               [50,60,70,80]
               ])
print(arr.dtype)

int32


In [14]:
arr= arr.astype(np.float64)
print(arr.dtype)

float64


### Exercise 5

In [15]:
arr1= np.array([1,2,3])
arr2=np.array([4,5,6])

In [17]:
arr_total = np.concatenate((arr1,arr2))
print(arr_total)

[1 2 3 4 5 6]


In [20]:
#second solution
arr_total2 = np.concatenate((arr1,arr2),axis=0)
print(arr_total)

[1 2 3 4 5 6]
